### ISSUE TITLE
1.1.3 無法啓動

### ISSUE THREAD

**Issue by foxlesbiao** [gnuf0rce/rss-helper#17]
`16:08:59 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
16:08:59 [INFO] https://github.com/iTXTech/mirai-console-loader
16:08:59 [INFO] This program is licensed under GNU AGPL v3
16:08:59 [INFO] Fetching Mirai Console Loader Announcement...
16:09:01 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

16:09:01 [INFO] Verifying "net.mamoe:mirai-console" v2.11.0-M1
16:09:02 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.11.0-M1
16:09:02 [INFO] Verifying "net.mamoe:mirai-core-all" v2.11.0-M1
16:09:03 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
16:09:03 [INFO] Verifying "net.mamoe:mirai-api-http" v1.10.0
16:09:04 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
16:09:04 [INFO] Verifying "rss-helper" v
16:09:04 [ERROR] Failed to verify package "rss-helper"
16:09:04 [ERROR] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.itxtech.mcl.component.Config$Package.getName(Config.java:120)
at org.itxtech.mcl.component.Config$Package.getBasename(Config.java:124)
at org.itxtech.mcl.component.Config$Package.getJarFile(Config.java:128)
at org.itxtech.mcl.Utility.checkLocalFile(Utility.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
at org.mozilla.javascript.Context.call(Context.java:554)
at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
at com.sun.proxy.$Proxy4.run(Unknown Source)
at org.itxtech.mcl.script.ScriptManager.phaseLoad(ScriptManager.java:98)
at org.itxtech.mcl.Loader.lambda$start$2(Loader.java:172)
at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
at org.itxtech.mcl.Loader.start(Loader.java:172)
at org.itxtech.mcl.Loader.main(Loader.java:68)

16:09:04 [INFO] Verifying "io.github.gnuf0rce:rss-helper" v1.1.2
16:09:04 [WARN] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Currentversion is 2.11.0-M1
16:09:04 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.11.0-M1
16:09:04 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 (boot.js#78)
at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
at script(boot.js:78)
at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
at org.mozilla.javascript.Context.call(Context.java:554)
at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
at com.sun.proxy.$Proxy4.run(Unknown Source)
at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
at org.itxtech.mcl.Loader.start(Loader.java:176)
at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.itxtech.mcl.component.Config$Package.getName(Config.java:120)
at org.itxtech.mcl.component.Config$Package.getBasename(Config.java:124)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
... 20 more

`

**Comment by foxlesbiao** [comment]
java 版本:11
JRE
