### ISSUE TITLE
java.lang.IllegalStateException: cannot upload forward message, failed on all servers.

### ISSUE THREAD

**Issue by voveer** [gnuf0rce/rss-helper#24]
我在大概半个月前使用本插件，遇到了mirai假死的问题，即无消息接收与发送（已订阅的也没有进行推送），当时以为是mirai问题所以用了几天就没用了，一周前在腾讯云Windows Server 2022上海机器部署的mirai安装了B站订阅插件与Chat Command，目前运行一周无任何错误，今天重新加载此插件，我去掉了doh（按照教程删掉），其他无任何改动。
```bash
# Dns Over Https Url
doh: ''
# Use IPv6
ipv6: false
# SNI HostName Remove Regex
sni: 
  - 'sukebei\.nyaa\.(si|net)'
# Http Timeout
timeout: 30000
# MAP(host, proxy), default by host=127.0.0.1
proxy: 
  www.google.com: 'http://127.0.0.1:8080'
  twitter.com: 'socks://127.0.0.1:1080'
# DNS CNAME
cname: 
  twimg.com: 
    - twimg.twitter.map.fastly.net
    - pbs.twimg.com.akamaized.net
```
mirai控制台内容为:
```bash
2023-11-18 14:08:31 W/mirai-skia-plugin: https://ghproxy.com/https://github.com/cssxsh/gif-jni/releases/download/v2.0.8/gif-windows-x64.dll
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
        at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

2023-11-18 14:09:13 E/mirai-skia-plugin: Exception in coroutine Plugin xyz.cssxsh.mirai.plugin.mirai-skia-plugin of mirai-skia-plugin
java.net.ConnectException: Failed to connect to github.com/20.205.243.166:443
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at mirai-skia-plugin-1.3.2.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 18 more
```

**Comment by voveer** [comment]
```bash
2023-11-18 14:42:12 W/rss-helper: 向 Group 脱敏处理(群号) 发送消息失败
java.lang.IllegalStateException: cannot upload forward message, failed on all servers.
        at net.mamoe.mirai.internal.network.highway.Highway.uploadResourceBdh(Highway.kt:448)
        at net.mamoe.mirai.internal.network.highway.Highway$uploadResourceBdh$1.invokeSuspend(Highway.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Unknown Source)
        at java.base/sun.nio.ch.Net.connect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/java.net.Socket.<init>(Unknown Source)
        at java.base/java.net.Socket.<init>(Unknown Source)
        at net.mamoe.mirai.internal.utils.PlatformSocket$connect$2.invoke(PlatformSocket.kt:91)
        at net.mamoe.mirai.internal.utils.PlatformSocket$connect$2.invoke(PlatformSocket.kt:90)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        ... 4 more
        Suppressed: java.net.ConnectException: Connection timed out: connect
                ... 22 more
        Suppressed: java.net.ConnectException: Connection timed out: connect
                ... 22 more
                Suppressed: java.net.ConnectException: Connection timed out: connect
                        ... 22 more
                Suppressed: java.net.ConnectException: Connection timed out: connect
                        ... 22 more
                        Suppressed: java.net.ConnectException: Connection timed out: connect
                                ... 22 more
                        Suppressed: java.net.ConnectException: Connection timed out: connect
                                ... 22 more
                                Suppressed: java.net.ConnectException: Connection timed out: connect
                                        ... 22 more
```
订阅链接:
```bash
https://biliup.me/atom/t/hwe/discussions
```

**Comment by cssxsh** [comment]
> cannot upload forward message, failed on all servers.

腾讯的问题，无法发送转发信息
